name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - run: |
          sudo apt-get update
          sudo apt-get install -y lftp

          lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }} <<EOF
          set ssl:verify-certificate no
          mirror -R --delete _site/ /public_html/2t8.net/yusquid/
          quit
          EOF
